// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package queries

import (
	"context"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    id,
    tenant_id,
    name,
    key_hash,
    scope,
    revoked_at,
    last_used_at,
    created_at,
    updated_at
FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Scope,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
