// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (
    id,
    tenant_id,
    actor_key_id,
    action,
    object_id,
    metadata,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING
    id,
    tenant_id,
    actor_key_id,
    action,
    object_id,
    metadata,
    created_at
`

type InsertAuditLogParams struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	ActorKeyID pgtype.UUID        `json:"actor_key_id"`
	Action     string             `json:"action"`
	ObjectID   pgtype.UUID        `json:"object_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ID,
		arg.TenantID,
		arg.ActorKeyID,
		arg.Action,
		arg.ObjectID,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorKeyID,
		&i.Action,
		&i.ObjectID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
