// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteChunksByVideoID = `-- name: DeleteChunksByVideoID :exec
DELETE FROM chunks
WHERE video_id = $1
  AND tenant_id = $2
`

type DeleteChunksByVideoIDParams struct {
	VideoID  string `json:"video_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) DeleteChunksByVideoID(ctx context.Context, arg DeleteChunksByVideoIDParams) error {
	_, err := q.db.Exec(ctx, deleteChunksByVideoID, arg.VideoID, arg.TenantID)
	return err
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO chunks (
    id,
    tenant_id,
    video_id,
    chunk_index,
    content,
    embedding,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING
    id,
    tenant_id,
    video_id,
    chunk_index,
    content,
    embedding,
    created_at
`

type InsertChunkParams struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	VideoID    string             `json:"video_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	Embedding  pgvector.Vector    `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, insertChunk,
		arg.ID,
		arg.TenantID,
		arg.VideoID,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
		arg.CreatedAt,
	)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VideoID,
		&i.ChunkIndex,
		&i.Content,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const searchChunks = `-- name: SearchChunks :many
SELECT
    c.id,
    c.tenant_id,
    c.video_id,
    c.chunk_index,
    c.content,
    c.created_at,
    v.title AS video_title
FROM chunks c
JOIN videos v ON v.id = c.video_id
WHERE c.tenant_id = $1
  AND v.status = 'completed'
  AND v.deleted_at IS NULL
  AND ($2::text IS NULL OR EXISTS (
      SELECT 1
      FROM video_segments vs
      JOIN segments s ON s.id = vs.segment_id
      WHERE vs.video_id = v.id
        AND s.tenant_id = $1
        AND lower(s.name) = lower($2)
  ))
ORDER BY c.embedding <=> $3::vector
LIMIT $4
`

type SearchChunksParams struct {
	TenantID    string          `json:"tenant_id"`
	SegmentName pgtype.Text     `json:"segment_name"`
	Embedding   pgvector.Vector `json:"embedding"`
	Limit       int32           `json:"limit"`
}

type SearchChunksRow struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	VideoID    string             `json:"video_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	VideoTitle string             `json:"video_title"`
}

func (q *Queries) SearchChunks(ctx context.Context, arg SearchChunksParams) ([]SearchChunksRow, error) {
	rows, err := q.db.Query(ctx, searchChunks,
		arg.TenantID,
		arg.SegmentName,
		arg.Embedding,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksRow
	for rows.Next() {
		var i SearchChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.VideoID,
			&i.ChunkIndex,
			&i.Content,
			&i.CreatedAt,
			&i.VideoTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
