// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingJob = `-- name: ClaimNextPendingJob :one
UPDATE jobs
SET status = 'processing',
    stage = 'downloading',
    started_at = COALESCE(started_at, now())
WHERE id = (
    SELECT id
    FROM jobs
    WHERE status = 'pending'
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
`

func (q *Queries) ClaimNextPendingJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimNextPendingJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UploadIntentID,
		&i.FileKey,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countJobs = `-- name: CountJobs :one
SELECT count(*)
FROM jobs
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
`

type CountJobsParams struct {
	TenantID string      `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
`

type CreateJobParams struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	UploadIntentID pgtype.UUID        `json:"upload_intent_id"`
	FileKey        string             `json:"file_key"`
	Title          string             `json:"title"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	Stage          string             `json:"stage"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	RetryCount     int32              `json:"retry_count"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.TenantID,
		arg.UploadIntentID,
		arg.FileKey,
		arg.Title,
		arg.Kind,
		arg.Status,
		arg.Stage,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.StartedAt,
		arg.FinishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UploadIntentID,
		&i.FileKey,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
FROM jobs
WHERE id = $1
  AND tenant_id = $2
`

type GetJobByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetJobByID(ctx context.Context, arg GetJobByIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, arg.ID, arg.TenantID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UploadIntentID,
		&i.FileKey,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIDAllTenants = `-- name: GetJobByIDAllTenants :one
SELECT
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByIDAllTenants(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIDAllTenants, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UploadIntentID,
		&i.FileKey,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
FROM jobs
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListJobsParams struct {
	TenantID string      `json:"tenant_id"`
	Status   pgtype.Text `json:"status"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.TenantID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UploadIntentID,
			&i.FileKey,
			&i.Title,
			&i.Kind,
			&i.Status,
			&i.Stage,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET status = 'pending',
    stage = 'queued',
    error_message = NULL,
    retry_count = retry_count + 1,
    started_at = NULL,
    finished_at = NULL
WHERE id = $1
  AND tenant_id = $2
  AND status = 'failed'
RETURNING
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
`

type RetryJobParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, retryJob, arg.ID, arg.TenantID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UploadIntentID,
		&i.FileKey,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status = $3,
    stage = $4,
    error_message = $5,
    started_at = COALESCE(started_at, CASE WHEN $3 = 'processing' THEN now() END),
    finished_at = CASE
        WHEN $3 IN ('completed', 'failed') THEN now()
        ELSE finished_at
    END
WHERE id = $1
  AND tenant_id = $2
RETURNING
    id,
    tenant_id,
    upload_intent_id,
    file_key,
    title,
    kind,
    status,
    stage,
    error_message,
    retry_count,
    started_at,
    finished_at,
    created_at,
    updated_at
`

type UpdateJobStatusParams struct {
	ID           string      `json:"id"`
	TenantID     string      `json:"tenant_id"`
	Status       string      `json:"status"`
	Stage        string      `json:"stage"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Stage,
		arg.ErrorMessage,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UploadIntentID,
		&i.FileKey,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
