// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ApiKey struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Scope      string             `json:"scope"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	ActorKeyID pgtype.UUID        `json:"actor_key_id"`
	Action     string             `json:"action"`
	ObjectID   pgtype.UUID        `json:"object_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Chunk struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	VideoID    string             `json:"video_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	Embedding  pgvector.Vector    `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	UploadIntentID pgtype.UUID        `json:"upload_intent_id"`
	FileKey        string             `json:"file_key"`
	Title          string             `json:"title"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	Stage          string             `json:"stage"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	RetryCount     int32              `json:"retry_count"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type JobSegment struct {
	JobID     string `json:"job_id"`
	SegmentID string `json:"segment_id"`
	TenantID  string `json:"tenant_id"`
}

type Segment struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Summary struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	VideoID      string             `json:"video_id"`
	Status       string             `json:"status"`
	Content      pgtype.Text        `json:"content"`
	Language     pgtype.Text        `json:"language"`
	Model        pgtype.Text        `json:"model"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Transcript struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	VideoID   string             `json:"video_id"`
	Content   string             `json:"content"`
	Language  pgtype.Text        `json:"language"`
	Model     pgtype.Text        `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UploadIntent struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	FileKey     string             `json:"file_key"`
	ContentType string             `json:"content_type"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Video struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	JobID           string             `json:"job_id"`
	Title           string             `json:"title"`
	Kind            string             `json:"kind"`
	FileKey         string             `json:"file_key"`
	Status          string             `json:"status"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type VideoSegment struct {
	VideoID   string `json:"video_id"`
	SegmentID string `json:"segment_id"`
	TenantID  string `json:"tenant_id"`
}
