// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachJobSegment = `-- name: AttachJobSegment :exec
INSERT INTO job_segments (
    job_id,
    segment_id,
    tenant_id
) VALUES (
    $1, $2, $3
)
ON CONFLICT DO NOTHING
`

type AttachJobSegmentParams struct {
	JobID     string `json:"job_id"`
	SegmentID string `json:"segment_id"`
	TenantID  string `json:"tenant_id"`
}

func (q *Queries) AttachJobSegment(ctx context.Context, arg AttachJobSegmentParams) error {
	_, err := q.db.Exec(ctx, attachJobSegment, arg.JobID, arg.SegmentID, arg.TenantID)
	return err
}

const attachVideoSegment = `-- name: AttachVideoSegment :exec
INSERT INTO video_segments (
    video_id,
    segment_id,
    tenant_id
) VALUES (
    $1, $2, $3
)
ON CONFLICT DO NOTHING
`

type AttachVideoSegmentParams struct {
	VideoID   string `json:"video_id"`
	SegmentID string `json:"segment_id"`
	TenantID  string `json:"tenant_id"`
}

func (q *Queries) AttachVideoSegment(ctx context.Context, arg AttachVideoSegmentParams) error {
	_, err := q.db.Exec(ctx, attachVideoSegment, arg.VideoID, arg.SegmentID, arg.TenantID)
	return err
}

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (
    id,
    tenant_id,
    name,
    created_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING
    id,
    tenant_id,
    name,
    created_at
`

type CreateSegmentParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, createSegment,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const ensureSegmentByName = `-- name: EnsureSegmentByName :one
WITH ins AS (
    INSERT INTO segments (id, tenant_id, name, created_at)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT DO NOTHING
    RETURNING id, tenant_id, name, created_at
)
SELECT id, tenant_id, name, created_at FROM ins
UNION ALL
SELECT id, tenant_id, name, created_at FROM segments
WHERE tenant_id = $2 AND lower(name) = lower($3)
LIMIT 1
`

type EnsureSegmentByNameParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EnsureSegmentByNameRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) EnsureSegmentByName(ctx context.Context, arg EnsureSegmentByNameParams) (EnsureSegmentByNameRow, error) {
	row := q.db.QueryRow(ctx, ensureSegmentByName,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	var i EnsureSegmentByNameRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSegmentByName = `-- name: GetSegmentByName :one
SELECT
    id,
    tenant_id,
    name,
    created_at
FROM segments
WHERE tenant_id = $1
  AND lower(name) = lower($2)
`

type GetSegmentByNameParams struct {
	TenantID string `json:"tenant_id"`
	Lower    string `json:"lower"`
}

func (q *Queries) GetSegmentByName(ctx context.Context, arg GetSegmentByNameParams) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegmentByName, arg.TenantID, arg.Lower)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listSegmentNamesByJobID = `-- name: ListSegmentNamesByJobID :many
SELECT s.name
FROM segments s
JOIN job_segments js ON js.segment_id = s.id
WHERE js.job_id = $1
  AND js.tenant_id = $2
ORDER BY s.name
`

type ListSegmentNamesByJobIDParams struct {
	JobID    string `json:"job_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) ListSegmentNamesByJobID(ctx context.Context, arg ListSegmentNamesByJobIDParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSegmentNamesByJobID, arg.JobID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentNamesByVideoID = `-- name: ListSegmentNamesByVideoID :many
SELECT s.name
FROM segments s
JOIN video_segments vs ON vs.segment_id = s.id
WHERE vs.video_id = $1
  AND vs.tenant_id = $2
ORDER BY s.name
`

type ListSegmentNamesByVideoIDParams struct {
	VideoID  string `json:"video_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) ListSegmentNamesByVideoID(ctx context.Context, arg ListSegmentNamesByVideoIDParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSegmentNamesByVideoID, arg.VideoID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
