// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSummaryByVideoID = `-- name: GetSummaryByVideoID :one
SELECT
    id,
    tenant_id,
    video_id,
    status,
    content,
    language,
    model,
    error_message,
    created_at,
    updated_at
FROM summaries
WHERE video_id = $1
  AND tenant_id = $2
`

type GetSummaryByVideoIDParams struct {
	VideoID  string `json:"video_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetSummaryByVideoID(ctx context.Context, arg GetSummaryByVideoIDParams) (Summary, error) {
	row := q.db.QueryRow(ctx, getSummaryByVideoID, arg.VideoID, arg.TenantID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VideoID,
		&i.Status,
		&i.Content,
		&i.Language,
		&i.Model,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSummary = `-- name: UpsertSummary :one
INSERT INTO summaries (
    id,
    tenant_id,
    video_id,
    status,
    content,
    language,
    model,
    error_message,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (video_id) DO UPDATE SET
    status = EXCLUDED.status,
    content = EXCLUDED.content,
    language = EXCLUDED.language,
    model = EXCLUDED.model,
    error_message = EXCLUDED.error_message
RETURNING
    id,
    tenant_id,
    video_id,
    status,
    content,
    language,
    model,
    error_message,
    created_at,
    updated_at
`

type UpsertSummaryParams struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	VideoID      string             `json:"video_id"`
	Status       string             `json:"status"`
	Content      pgtype.Text        `json:"content"`
	Language     pgtype.Text        `json:"language"`
	Model        pgtype.Text        `json:"model"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSummary(ctx context.Context, arg UpsertSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, upsertSummary,
		arg.ID,
		arg.TenantID,
		arg.VideoID,
		arg.Status,
		arg.Content,
		arg.Language,
		arg.Model,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VideoID,
		&i.Status,
		&i.Content,
		&i.Language,
		&i.Model,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
