// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcripts.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertTranscript = `-- name: UpsertTranscript :one
INSERT INTO transcripts (
    id,
    tenant_id,
    video_id,
    content,
    language,
    model,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (video_id) DO UPDATE SET
    content = EXCLUDED.content,
    language = EXCLUDED.language,
    model = EXCLUDED.model
RETURNING
    id,
    tenant_id,
    video_id,
    content,
    language,
    model,
    created_at
`

type UpsertTranscriptParams struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	VideoID   string             `json:"video_id"`
	Content   string             `json:"content"`
	Language  pgtype.Text        `json:"language"`
	Model     pgtype.Text        `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, upsertTranscript,
		arg.ID,
		arg.TenantID,
		arg.VideoID,
		arg.Content,
		arg.Language,
		arg.Model,
		arg.CreatedAt,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VideoID,
		&i.Content,
		&i.Language,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
