// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_intents.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadIntent = `-- name: CreateUploadIntent :one
INSERT INTO upload_intents (
    id,
    tenant_id,
    file_key,
    content_type,
    status,
    expires_at,
    consumed_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING
    id,
    tenant_id,
    file_key,
    content_type,
    status,
    expires_at,
    consumed_at,
    created_at
`

type CreateUploadIntentParams struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	FileKey     string             `json:"file_key"`
	ContentType string             `json:"content_type"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUploadIntent(ctx context.Context, arg CreateUploadIntentParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, createUploadIntent,
		arg.ID,
		arg.TenantID,
		arg.FileKey,
		arg.ContentType,
		arg.Status,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.CreatedAt,
	)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileKey,
		&i.ContentType,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadIntentByFileKeyForUpdate = `-- name: GetUploadIntentByFileKeyForUpdate :one
SELECT
    id,
    tenant_id,
    file_key,
    content_type,
    status,
    expires_at,
    consumed_at,
    created_at
FROM upload_intents
WHERE file_key = $1
  AND tenant_id = $2
FOR UPDATE
`

type GetUploadIntentByFileKeyForUpdateParams struct {
	FileKey  string `json:"file_key"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetUploadIntentByFileKeyForUpdate(ctx context.Context, arg GetUploadIntentByFileKeyForUpdateParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, getUploadIntentByFileKeyForUpdate, arg.FileKey, arg.TenantID)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileKey,
		&i.ContentType,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markUploadIntentConsumed = `-- name: MarkUploadIntentConsumed :one
UPDATE upload_intents
SET status = 'consumed',
    consumed_at = now()
WHERE file_key = $1
  AND tenant_id = $2
  AND status = 'issued'
RETURNING
    id,
    tenant_id,
    file_key,
    content_type,
    status,
    expires_at,
    consumed_at,
    created_at
`

type MarkUploadIntentConsumedParams struct {
	FileKey  string `json:"file_key"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) MarkUploadIntentConsumed(ctx context.Context, arg MarkUploadIntentConsumedParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, markUploadIntentConsumed, arg.FileKey, arg.TenantID)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileKey,
		&i.ContentType,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
