// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    id,
    tenant_id,
    job_id,
    title,
    kind,
    file_key,
    status,
    duration_seconds,
    deleted_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING
    id,
    tenant_id,
    job_id,
    title,
    kind,
    file_key,
    status,
    duration_seconds,
    deleted_at,
    created_at,
    updated_at
`

type CreateVideoParams struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	JobID           string             `json:"job_id"`
	Title           string             `json:"title"`
	Kind            string             `json:"kind"`
	FileKey         string             `json:"file_key"`
	Status          string             `json:"status"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.ID,
		arg.TenantID,
		arg.JobID,
		arg.Title,
		arg.Kind,
		arg.FileKey,
		arg.Status,
		arg.DurationSeconds,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.Title,
		&i.Kind,
		&i.FileKey,
		&i.Status,
		&i.DurationSeconds,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT
    id,
    tenant_id,
    job_id,
    title,
    kind,
    file_key,
    status,
    duration_seconds,
    deleted_at,
    created_at,
    updated_at
FROM videos
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetVideoByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetVideoByID(ctx context.Context, arg GetVideoByIDParams) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, arg.ID, arg.TenantID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.Title,
		&i.Kind,
		&i.FileKey,
		&i.Status,
		&i.DurationSeconds,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT
    v.id,
    v.tenant_id,
    v.job_id,
    v.title,
    v.kind,
    v.file_key,
    v.status,
    v.duration_seconds,
    v.deleted_at,
    v.created_at,
    v.updated_at
FROM videos v
WHERE v.tenant_id = $1
  AND v.deleted_at IS NULL
  AND ($2::text IS NULL OR v.status = $2)
  AND ($3::text IS NULL OR EXISTS (
      SELECT 1
      FROM video_segments vs
      JOIN segments s ON s.id = vs.segment_id
      WHERE vs.video_id = v.id
        AND s.tenant_id = $1
        AND lower(s.name) = lower($3)
  ))
ORDER BY v.created_at DESC
LIMIT $5
OFFSET $4
`

type ListVideosParams struct {
	TenantID    string      `json:"tenant_id"`
	Status      pgtype.Text `json:"status"`
	SegmentName pgtype.Text `json:"segment_name"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos,
		arg.TenantID,
		arg.Status,
		arg.SegmentName,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.JobID,
			&i.Title,
			&i.Kind,
			&i.FileKey,
			&i.Status,
			&i.DurationSeconds,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVideo = `-- name: SoftDeleteVideo :one
UPDATE videos
SET deleted_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
RETURNING
    id,
    tenant_id,
    job_id,
    title,
    kind,
    file_key,
    status,
    duration_seconds,
    deleted_at,
    created_at,
    updated_at
`

type SoftDeleteVideoParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) SoftDeleteVideo(ctx context.Context, arg SoftDeleteVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, softDeleteVideo, arg.ID, arg.TenantID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.Title,
		&i.Kind,
		&i.FileKey,
		&i.Status,
		&i.DurationSeconds,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :one
UPDATE videos
SET status = $3
WHERE id = $1
  AND tenant_id = $2
RETURNING
    id,
    tenant_id,
    job_id,
    title,
    kind,
    file_key,
    status,
    duration_seconds,
    deleted_at,
    created_at,
    updated_at
`

type UpdateVideoStatusParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideoStatus, arg.ID, arg.TenantID, arg.Status)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.JobID,
		&i.Title,
		&i.Kind,
		&i.FileKey,
		&i.Status,
		&i.DurationSeconds,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
